-- Criação do banco de dados
CREATE DATABASE IF NOT EXISTS Clinica;
USE Clinica;

-- Tabela Recepcionista
CREATE TABLE Recepcionista (
    CPF_RECEP VARCHAR(11) PRIMARY KEY,
    TELEFONE VARCHAR(15) NOT NULL,
    NOME VARCHAR(100) NOT NULL
);

-- Tabela Medico
CREATE TABLE Medico (
    CRM VARCHAR(10) PRIMARY KEY,
    ESPEC VARCHAR(100) NOT NULL,
    TEL VARCHAR(15) NOT NULL,
    NOME VARCHAR(100) NOT NULL
);

-- Tabela ConvenioMedico
CREATE TABLE ConvenioMedico (
    CODIGO_CONV INT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    PORCENTAGEM_COBERTURA DECIMAL(5,2) NOT NULL
);

-- Tabela Paciente
CREATE TABLE Paciente (
    CPF_PACIENTE VARCHAR(11) PRIMARY KEY,
    CODIGO_CONVENIO INT NULL,
    DT_NASC DATE NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    ENDERECO VARCHAR(200) NOT NULL, 
    FOREIGN KEY (CODIGO_CONVENIO) REFERENCES ConvenioMedico(CODIGO_CONV)
);

-- Tabela Consulta
CREATE TABLE Consulta (
    ID_CONSULTA INT PRIMARY KEY AUTO_INCREMENT,
    CPF_RECEP VARCHAR(11) NOT NULL,
    CPF_PACIENTE VARCHAR(11) NOT NULL,
    CRM_MED VARCHAR(10) NOT NULL,
    HORA TIME NOT NULL,
    DATA DATE NOT NULL,
    STATUS ENUM('agendada', 'concluida', 'cancelada') NOT NULL,
    FOREIGN KEY (CPF_RECEP) REFERENCES Recepcionista(CPF_RECEP),
    FOREIGN KEY (CPF_PACIENTE) REFERENCES Paciente(CPF_PACIENTE),
    FOREIGN KEY (CRM_MED) REFERENCES Medico(CRM)
);

-- Tabela ProcedimentoMedico
CREATE TABLE ProcedimentoMedico (
    CODIGO_PRO INT PRIMARY KEY,
    TEMPO TIME NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL,
    NOME VARCHAR(100) NOT NULL
);

-- Tabela GeraProcedimento (relacionamento N:M entre Consulta e ProcedimentoMedico)
CREATE TABLE GeraProcedimento (
    ID_CONSULTA INT,
    CODIGO_PRO INT,
    PRIMARY KEY (ID_CONSULTA, CODIGO_PRO),
    FOREIGN KEY (ID_CONSULTA) REFERENCES Consulta(ID_CONSULTA),
    FOREIGN KEY (CODIGO_PRO) REFERENCES ProcedimentoMedico(CODIGO_PRO)
);

-- Tabela CoberturaConvenio (relacionamento N:M entre ConvenioMedico e ProcedimentoMedico)
CREATE TABLE CoberturaConvenio (
    CODIGO_CONV INT,
    CODIGO_PRO INT,
    PRIMARY KEY (CODIGO_CONV, CODIGO_PRO),
    FOREIGN KEY (CODIGO_CONV) REFERENCES ConvenioMedico(CODIGO_CONV),
    FOREIGN KEY (CODIGO_PRO) REFERENCES ProcedimentoMedico(CODIGO_PRO)
);

-- Tabela Pagamento
CREATE TABLE Pagamento (
    ID_PAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    CODIGO_CONV INT NULL,
    CPF_PACIENTE VARCHAR(11) NULL,
    ID_CONSULTA INT NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL,
    FORMA ENUM('cartao', 'dinheiro', 'boleto') NOT NULL,
    STATUS ENUM('pago', 'pendente', 'cancelado') NOT NULL,
    DATA DATE NULL,
    FOREIGN KEY (CODIGO_CONV) REFERENCES ConvenioMedico(CODIGO_CONV),
    FOREIGN KEY (CPF_PACIENTE) REFERENCES Paciente(CPF_PACIENTE),
    FOREIGN KEY (ID_CONSULTA) REFERENCES Consulta(ID_CONSULTA),
    CHECK (CODIGO_CONV IS NOT NULL OR CPF_PACIENTE IS NOT NULL)
);